_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.13.0
            "5": 0.19.11
            "8":
                - 2
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
action_ask_vol:
    value: true
action_dim:
    value: 2
actions:
    value:
        - 0
        - 1
alpha:
    value: 0.95
alpha_ramp:
    value: 15
arrival_price:
    value: 100.005
basic_state:
    value: true
batch_size:
    value: 64
dynamic_batch_size:
    value: false
dynamic_lr:
    value: false
episodes:
    value: 5000
eps:
    value: 0.01
epsilon_decay:
    value: 0.995
epsilon_end:
    value: 0
epsilon_start:
    value: 1
exec_security_margin:
    value: 1
file_name:
    value: qrm_paper.npy
file_name_ask:
    value: qrm_paper.npy
file_name_bid:
    value: qrm_paper.npy
final_penalty:
    value: 1
folder_path_intensity_table:
    value: calibration_data/intensity_table/
folder_path_invariant:
    value: calibration_data/invariant_distribution/
gamma:
    value: 1
history_size:
    value: 1
initial_inventory:
    value: 30
learning_rate:
    value: 0.0001
len_state_lob:
    value: 3
logging_every:
    value: 10
max_events:
    value: 2200000
max_events_intra:
    value: 200000
memory_capacity:
    value: 300000
mode:
    value: train
normal_prices:
    value: true
price_offset:
    value: 0
price_std:
    value: 0.3
proba_0:
    value: 0.5
prop_deter_strats:
    value: 0
prop_greedy_eps:
    value: 0.09
risk_aversion:
    value: 0
safety_test:
    value: false
seed:
    value: 42
state_dim:
    value: 3
target_update_freq:
    value: 100
target_update_freq_2:
    value: 100
theta:
    value: 0.6
theta_reinit:
    value: 0.85
tick:
    value: 0.01
time_horizon:
    value: 10000
trader_time_step:
    value: 1000
trader_times:
    value:
        - 0
        - 1000
        - 2000
        - 3000
        - 4000
        - 5000
        - 6000
        - 7000
        - 8000
        - 9000
        - 10000
unif_deter_strats:
    value: false
vol_offset:
    value: 5
vol_std:
    value: 4
warmup_steps:
    value: 64
