_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_episode_storage:
    value: None
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: '[[ 1.         -0.8        -0.01666667]]'
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x000002546AB0C440>
_n_calls:
    value: 0
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 200
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 17
                - 22
                - 55
                - 61
            "4": 3.13.0
            "5": 0.20.1
            "8":
                - 2
                - 3
            "12": 0.20.1
            "13": windows-amd64
action_ask_vol:
    value: true
action_dim:
    value: 2
action_noise:
    value: None
action_space:
    value: Discrete(2)
actions:
    value:
        - 0
        - 1
algo:
    value: DQN
alpha:
    value: 0.95
alpha_ramp:
    value: 15
arrival_price:
    value: 100.005
basic_state:
    value: true
batch_norm_stats:
    value: '[]'
batch_norm_stats_target:
    value: '[]'
batch_size:
    value: 64
buffer_size:
    value: 300000
device:
    value: cuda
dynamic_batch_size:
    value: false
dynamic_lr:
    value: false
env:
    value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x000002545782D550>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
episodes:
    value: 20
eps:
    value: 0.01
epsilon_decay:
    value: 0.995
epsilon_end:
    value: 0
epsilon_start:
    value: 1
exec_security_margin:
    value: 1
exploration_final_eps:
    value: 0
exploration_fraction:
    value: 0.25
exploration_initial_eps:
    value: 1
exploration_rate:
    value: 0
exploration_schedule:
    value: <function get_linear_fn.<locals>.func at 0x000002545CB977E0>
file_name:
    value: qrm_paper.npy
file_name_ask:
    value: qrm_paper.npy
file_name_bid:
    value: qrm_paper.npy
final_penalty:
    value: 1
folder_path_intensity_table:
    value: calibration_data/intensity_table/
folder_path_invariant:
    value: calibration_data/invariant_distribution/
gamma:
    value: 1
gradient_steps:
    value: 1
history_size:
    value: 1
initial_inventory:
    value: 30
learning_rate:
    value: 0.0001
learning_starts:
    value: 100
len_state_lob:
    value: 3
logging_every:
    value: 10
lr_schedule:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x000002545783B740>
max_events:
    value: 2200000
max_events_intra:
    value: 200000
max_grad_norm:
    value: 10
memory_capacity:
    value: 300000
mode:
    value: train
n_envs:
    value: 1
normal_prices:
    value: true
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (3,), float32)
optimize_memory_usage:
    value: "False"
policy:
    value: |-
        DQNPolicy(
          (q_net): QNetwork(
            (features_extractor): FlattenExtractor(
              (flatten): Flatten(start_dim=1, end_dim=-1)
            )
            (q_net): Sequential(
              (0): Linear(in_features=3, out_features=30, bias=True)
              (1): LeakyReLU(negative_slope=0.01)
              (2): Linear(in_features=30, out_features=30, bias=True)
              (3): LeakyReLU(negative_slope=0.01)
              (4): Linear(in_features=30, out_features=30, bias=True)
              (5): LeakyReLU(negative_slope=0.01)
              (6): Linear(in_features=30, out_features=30, bias=True)
              (7): LeakyReLU(negative_slope=0.01)
              (8): Linear(in_features=30, out_features=30, bias=True)
              (9): LeakyReLU(negative_slope=0.01)
              (10): Linear(in_features=30, out_features=2, bias=True)
            )
          )
          (q_net_target): QNetwork(
            (features_extractor): FlattenExtractor(
              (flatten): Flatten(start_dim=1, end_dim=-1)
            )
            (q_net): Sequential(
              (0): Linear(in_features=3, out_features=30, bias=True)
              (1): LeakyReLU(negative_slope=0.01)
              (2): Linear(in_features=30, out_features=30, bias=True)
              (3): LeakyReLU(negative_slope=0.01)
              (4): Linear(in_features=30, out_features=30, bias=True)
              (5): LeakyReLU(negative_slope=0.01)
              (6): Linear(in_features=30, out_features=30, bias=True)
              (7): LeakyReLU(negative_slope=0.01)
              (8): Linear(in_features=30, out_features=30, bias=True)
              (9): LeakyReLU(negative_slope=0.01)
              (10): Linear(in_features=30, out_features=2, bias=True)
            )
          )
        )
policy_class:
    value: <class 'stable_baselines3.dqn.policies.DQNPolicy'>
policy_kwargs:
    value: '{''net_arch'': [30, 30, 30, 30, 30], ''activation_fn'': <class ''torch.nn.modules.activation.LeakyReLU''>}'
price_offset:
    value: 0
price_std:
    value: 0.3
proba_0:
    value: 0.5
prop_deter_strats:
    value: 0
prop_greedy_eps:
    value: 0.25
q_net:
    value: |-
        QNetwork(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (q_net): Sequential(
            (0): Linear(in_features=3, out_features=30, bias=True)
            (1): LeakyReLU(negative_slope=0.01)
            (2): Linear(in_features=30, out_features=30, bias=True)
            (3): LeakyReLU(negative_slope=0.01)
            (4): Linear(in_features=30, out_features=30, bias=True)
            (5): LeakyReLU(negative_slope=0.01)
            (6): Linear(in_features=30, out_features=30, bias=True)
            (7): LeakyReLU(negative_slope=0.01)
            (8): Linear(in_features=30, out_features=30, bias=True)
            (9): LeakyReLU(negative_slope=0.01)
            (10): Linear(in_features=30, out_features=2, bias=True)
          )
        )
q_net_target:
    value: |-
        QNetwork(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (q_net): Sequential(
            (0): Linear(in_features=3, out_features=30, bias=True)
            (1): LeakyReLU(negative_slope=0.01)
            (2): Linear(in_features=30, out_features=30, bias=True)
            (3): LeakyReLU(negative_slope=0.01)
            (4): Linear(in_features=30, out_features=30, bias=True)
            (5): LeakyReLU(negative_slope=0.01)
            (6): Linear(in_features=30, out_features=30, bias=True)
            (7): LeakyReLU(negative_slope=0.01)
            (8): Linear(in_features=30, out_features=30, bias=True)
            (9): LeakyReLU(negative_slope=0.01)
            (10): Linear(in_features=30, out_features=2, bias=True)
          )
        )
replay_buffer:
    value: <stable_baselines3.common.buffers.ReplayBuffer object at 0x000002545782D400>
replay_buffer_class:
    value: <class 'stable_baselines3.common.buffers.ReplayBuffer'>
replay_buffer_kwargs:
    value: '{}'
risk_aversion:
    value: 0
safety_test:
    value: false
sde_sample_freq:
    value: -1
seed:
    value: 42
start_time:
    value: 1753193527898171700
state_dim:
    value: 3
target_update_freq:
    value: 100
target_update_freq_2:
    value: 100
target_update_interval:
    value: 100
tau:
    value: 1
tensorboard_log:
    value: None
theta:
    value: 0.6
theta_reinit:
    value: 0.85
tick:
    value: 0.01
time_horizon:
    value: 10000
total_timesteps:
    value: 200
trader_time_step:
    value: 1000
trader_times:
    value:
        - 0
        - 1000
        - 2000
        - 3000
        - 4000
        - 5000
        - 6000
        - 7000
        - 8000
        - 9000
        - 10000
train_freq:
    value: 'TrainFreq(frequency=1, unit=<TrainFrequencyUnit.STEP: ''step''>)'
unif_deter_strats:
    value: false
use_sde:
    value: "False"
use_sde_at_warmup:
    value: "False"
verbose:
    value: 1
vol_offset:
    value: 5
vol_std:
    value: 4
warmup_steps:
    value: 64
